# Generated by Django 3.0.5 on 2020-04-21 17:35

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cross',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=63)),
                ('begins_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('users', models.ManyToManyField(related_name='crosses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=63)),
                ('description', models.CharField(max_length=300)),
                ('lattitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('answer', models.CharField(max_length=63)),
                ('serial_number', models.SmallIntegerField()),
                ('cross', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crosses.Cross')),
            ],
            options={
                'unique_together': {('cross', 'serial_number')},
            },
        ),
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('event', models.CharField(choices=[('GET_PROMPT', 'GET_PROMPT'), ('RIGHT_ANSWER', 'RIGHT_ANSWER'), ('WRONG_ANSWER', 'WRONG_ANSWER')], max_length=15)),
                ('details', django.contrib.postgres.fields.jsonb.JSONField()),
                ('penalty', models.DurationField()),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crosses.Mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=300)),
                ('serial_number', models.SmallIntegerField()),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crosses.Mission')),
            ],
            options={
                'unique_together': {('mission', 'serial_number')},
            },
        ),
    ]
