# Generated by Django 3.0.5 on 2020-04-30 15:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crosses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['cross', 'serial_number']},
        ),
        migrations.AlterModelOptions(
            name='progresslog',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='cross',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mission',
            name='cross',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='crosses.Cross'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='progresslog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='progresslog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='progresslog',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='crosses.Mission'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='crosses.Mission'),
        ),
        migrations.AddIndex(
            model_name='progresslog',
            index=models.Index(fields=['created_at'], name='crosses_pro_created_183fd2_idx'),
        ),
    ]
