# Generated by Django 3.0.5 on 2020-05-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosses', '0002_auto_20200430_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresslog',
            name='event',
            field=models.CharField(choices=[('GET_PROMPT', 'Get Prompt'), ('RIGHT_ANSWER', 'Right Answer'), ('WRONG_ANSWER', 'Wrong Answer')], max_length=15),
        ),
    ]
