# Generated by Django 3.0.5 on 2020-05-11 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crosses', '0003_auto_20200511_0700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['cross', 'sn']},
        ),
        migrations.RenameField(
            model_name='mission',
            old_name='lattitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='mission',
            old_name='longitude',
            new_name='lon',
        ),
        migrations.RenameField(
            model_name='mission',
            old_name='serial_number',
            new_name='sn',
        ),
        migrations.RenameField(
            model_name='prompt',
            old_name='serial_number',
            new_name='sn',
        ),
        migrations.AlterUniqueTogether(
            name='mission',
            unique_together={('cross', 'sn')},
        ),
        migrations.AlterUniqueTogether(
            name='prompt',
            unique_together={('mission', 'sn')},
        ),
    ]
