# Generated by Django 3.0.5 on 2020-05-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosses', '0005_update_details_sn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='lat',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
        migrations.AlterField(
            model_name='mission',
            name='lon',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
    ]
